# Exported from Render on 2025-12-09T11:29:07Z
version: "1"
projects:
- name: anagram
  environments:
  - name: Production
    services:
    - type: web
      name: anagram-searcher
      runtime: docker
      repo: https://github.com/Silvesb/wordbase-importer
      plan: free
      envVars:
      - key: APP_KEY
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_SSLMODE
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_CONNECTION
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_NAME
        sync: false
      - key: VITE_APP_NAME
        sync: false
      - key: AWS_BUCKET
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: MAIL_FROM_NAME
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_MAILER
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_CLIENT
        sync: false
      - key: CACHE_STORE
        sync: false
      - key: QUEUE_CONNECTION
        sync: false
      - key: FILESYSTEM_DISK
        sync: false
      - key: BROADCAST_CONNECTION
        sync: false
      - key: SESSION_LIFETIME
        sync: false
      - key: SESSION_DRIVER
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: LOG_STACK
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: APP_MAINTENANCE_DRIVER
        sync: false
      - key: APP_FAKER_LOCALE
        sync: false
      - key: APP_FALLBACK_LOCALE
        sync: false
      - key: APP_LOCALE
        sync: false
      - key: APP_DEBUG
        sync: false
      - key: APP_ENV
        sync: false
      region: frankfurt
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
